name: MazeTour
version: '${project.version}'
main: komok.org.example.mazetour.MazeTour
api-version: '1.20'
commands:
  boatrace:
    description: Старт
    permission: mazefun.boatrace
  world:
    description: Действие с миром
    permission: mazefun.world