name: MazeTour
version: '${project.version}'
main: komok.org.example.mazetour.MazeTour
api-version: '1.20'
commands:
  boatrace:
    description: Гонка на лодках
    permission: mazefun.boatrace
  candywar:
    description: Конфетные войны
    permission: mazefun.candywar
  world:
    description: Действие с миром
    permission: mazefun.world